# Generated by Django 3.2.11 on 2022-01-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgdetails',
            name='year_of_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='What year was your project started?'),
        ),
    ]
