# Generated by Django 3.1.7 on 2021-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsoc.userprofile',),
        ),
    ]
