# Generated by Django 3.2.11 on 2022-01-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0002_alter_suborgdetails_year_of_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborgdetails',
            name='past_years',
        ),
    ]
