# Generated by Django 3.1.7 on 2021-03-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0002_userprofileproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileProxy',
        ),
        migrations.CreateModel(
            name='AdminGSOCInvites',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsoc.userprofile',),
        ),
    ]
