# Generated by Django 3.1.13 on 2021-11-22 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsoc', '0003_auto_20210322_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborgdetails',
            name='suborg_admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='suborg_admin', to='auth.user'),
            preserve_default=False,
        ),
    ]
