# Generated by Django 3.2.11 on 2022-02-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0004_auto_20220121_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuborgProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsoc.userprofile',),
        ),
    ]
