# Generated by Django 2.1.7 on 2019-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0004_auto_20190219_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='last_error',
            field=models.TextField(default=None, null=True),
        ),
    ]
