# Generated by Django 3.1.13 on 2021-11-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsoc', '0004_suborgdetails_suborg_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgdetails',
            name='suborg_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suborg_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
