# Generated by Django 2.1.7 on 2019-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0005_auto_20190219_1253")]

    operations = [
        migrations.AlterField(
            model_name="scheduler", name="success", field=models.BooleanField(null=True)
        )
    ]
