# Generated by Django 3.1.13 on 2022-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0005_suborgprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotAcceptedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsoc.reglink',),
        ),
    ]
