# Generated by Django 3.1.13 on 2022-06-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0006_notaccepteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='bpdd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsoc.blogpostduedate'),
        ),
        migrations.AddField(
            model_name='builder',
            name='timeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gsoc.timeline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='builder',
            name='category',
            field=models.CharField(choices=[('build_pre_blog_reminders', 'build_pre_blog_reminders'), ('build_post_blog_reminders', 'build_post_blog_reminders'), ('build_revoke_student_perms', 'build_revoke_student_perms'), ('build_remove_user_details', 'build_remove_user_details'), ('build_add_timeline_to_calendar', 'build_add_timeline_to_calendar'), ('build_add_bpdd_to_calendar', 'build_add_bpdd_to_calendar')], max_length=40),
        ),
    ]
