# Generated by Django 2.1.7 on 2019-03-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0006_auto_20190219_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrgForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=40)),
                ('Why_you_want_to_participate', models.CharField(max_length=200)),
                ('num_of_mentor', models.IntegerField()),
                ('suborg_admin_email', models.EmailField(max_length=254)),
                ('mentor_email', models.EmailField(max_length=254)),
                ('schedule', models.CharField(max_length=200)),
                ('get_involve', models.CharField(max_length=200)),
                ('keep_involve', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default='no')),
                ('accepted_years', models.CharField(max_length=70)),
                ('is_suborg', models.BooleanField()),
                ('participated_years', models.CharField(max_length=10)),
                ('not_selected_years', models.IntegerField()),
                ('project_started', models.IntegerField()),
                ('source_code', models.URLField()),
                ('url', models.URLField()),
                ('anything', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=30)),
                ('website_url', models.URLField()),
                ('desc', models.CharField(max_length=250)),
                ('irc_help', models.URLField()),
                ('mailing_list', models.URLField()),
                ('twitter', models.URLField()),
                ('blog', models.URLField()),
            ],
        ),
    ]
