# Generated by Django 3.2.11 on 2022-06-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0006_notaccepteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsoc.timeline'),
        ),
    ]
