# Generated by Django 3.2.11 on 2022-07-03 14:24

from django.db import migrations, models
import django.db.models.deletion
import gsoc.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0007_builder_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='builder',
            name='bpdd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsoc.blogpostduedate'),
        ),
        migrations.AddField(
            model_name='builder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsoc.event'),
        ),
        migrations.AlterField(
            model_name='blogpostduedate',
            name='title',
            field=models.CharField(default='Loading...', max_length=100),
        ),
        migrations.AlterField(
            model_name='builder',
            name='category',
            field=models.CharField(choices=[('build_pre_blog_reminders', 'build_pre_blog_reminders'), ('build_post_blog_reminders', 'build_post_blog_reminders'), ('build_revoke_student_perms', 'build_revoke_student_perms'), ('build_remove_user_details', 'build_remove_user_details'), ('build_add_timeline_to_calendar', 'build_add_timeline_to_calendar'), ('build_add_bpdd_to_calendar', 'build_add_bpdd_to_calendar'), ('build_add_event_to_calendar', 'build_add_event_to_calendar')], max_length=40),
        ),
        migrations.AlterField(
            model_name='builder',
            name='timeline',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gsoc.timeline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gsocyear',
            name='gsoc_year',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[gsoc.models.validate_date]),
        ),
    ]
