# Generated by Django 3.1.13 on 2022-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0007_builder_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
            ],
        ),
    ]
