# Generated by Django 2.1.7 on 2019-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0007_suborgform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborgform',
            old_name='anything',
            new_name='A very short description of your organization.',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='desc',
            new_name='Anything Else ?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='participated_years',
            new_name='For each year your organization has participated, provide the counts of successful and total students. (e.g. 2016: 3/4)',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='accepted',
            new_name='Has your org been accepted as a mentor org in Google Summer of Code before?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='not_selected_years',
            new_name='How many potential mentors have agreed to mentor this year?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='Why_you_want_to_participate',
            new_name='How will you get your students involved in your community during GSoC?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='get_involve',
            new_name='How will you help your students stay on schedule to complete their projects?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='keep_involve',
            new_name='How will you keep students involved with your community after GSoC?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='source_code',
            new_name='Idea List',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='num_of_mentor',
            new_name='If your org has applied for GSoC before but not been accepted, write the years. e.g 2005,2017,2018',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='is_suborg',
            new_name='Was this as a Suborg?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='project_started',
            new_name='What year was your project started?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='accepted_years',
            new_name='Which years did your org participate in GSoC?',
        ),
        migrations.RenameField(
            model_name='suborgform',
            old_name='schedule',
            new_name='Why does your org want to participate in Google Summer of Code?',
        ),
        migrations.RemoveField(
            model_name='suborgform',
            name='url',
        ),
        migrations.RemoveField(
            model_name='suborgform',
            name='website_url',
        ),
        migrations.AddField(
            model_name='suborgform',
            name='License Name',
            field=models.CharField(default='MIT', max_length=10),
        ),
        migrations.AddField(
            model_name='suborgform',
            name='Please provide URLs that point to repositories, GitHub organizations, or a web page that describes how to get your source code.',
            field=models.URLField(default='xyz'),
        ),
        migrations.AddField(
            model_name='suborgform',
            name='Website URL',
            field=models.URLField(default='xyz'),
        ),
        migrations.AddField(
            model_name='suborgform',
            name='Where does your source code live?',
            field=models.URLField(default='https://github.com/XYZ'),
        ),
    ]
