# Generated by Django 2.1.7 on 2019-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0007_auto_20190303_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='accepted_proposal_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
