# Generated by Django 2.1.7 on 2019-03-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0008_auto_20190303_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accepted_proposal_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
