# Generated by Django 3.2.13 on 2022-07-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0008_auto_20220703_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsocenddate',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='category',
            field=models.CharField(choices=[('build_pre_blog_reminders', 'build_pre_blog_reminders'), ('build_post_blog_reminders', 'build_post_blog_reminders'), ('build_revoke_student_perms', 'build_revoke_student_perms'), ('build_remove_user_details', 'build_remove_user_details'), ('build_add_timeline_to_calendar', 'build_add_timeline_to_calendar'), ('build_add_bpdd_to_calendar', 'build_add_bpdd_to_calendar'), ('build_add_event_to_calendar', 'build_add_event_to_calendar'), ('build_add_end_to_calendar', 'build_add_end_to_calendar')], max_length=40),
        ),
        migrations.AlterField(
            model_name='builder',
            name='timeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gsoc.timeline'),
        ),
    ]
