# Generated by Django 2.1.7 on 2019-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0009_auto_20190303_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_proposal_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
