# Generated by Django 3.2.13 on 2022-07-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0009_auto_20220709_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Weekly Check-In'), (1, 'Blog Post')], null=True)),
                ('daysOffset', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gsoc_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='category',
            field=models.CharField(choices=[('build_pre_blog_reminders', 'build_pre_blog_reminders'), ('build_post_blog_reminders', 'build_post_blog_reminders'), ('build_revoke_student_perms', 'build_revoke_student_perms'), ('build_remove_user_details', 'build_remove_user_details'), ('build_add_timeline_to_calendar', 'build_add_timeline_to_calendar'), ('build_add_bpdd_to_calendar', 'build_add_bpdd_to_calendar'), ('build_add_event_to_calendar', 'build_add_event_to_calendar'), ('build_add_end_to_calendar', 'build_add_end_to_calendar'), ('build_add_start_to_calendar', 'build_add_start_to_calendar')], max_length=40),
        ),
        migrations.CreateModel(
            name='GsocStartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gsoc.timeline')),
            ],
        ),
    ]
