# Generated by Django 3.2.13 on 2022-07-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0010_auto_20220710_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsoc.timeline'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='daysOffset',
            field=models.IntegerField(default=0),
        ),
    ]
