# Generated by Django 2.1.8 on 2019-04-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0011_userprofile_app_config")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scheduler",
            name="last_error",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
