# Generated by Django 3.2.13 on 2022-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0011_auto_20220710_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='daysOffset',
        ),
        migrations.AddField(
            model_name='generator',
            name='recurDays',
            field=models.IntegerField(default=7),
        ),
    ]
