# Generated by Django 3.2.13 on 2022-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0012_auto_20220711_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
