# Generated by Django 2.1.8 on 2019-04-18 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('gsoc', '0012_auto_20190418_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cms.Page')),
                ('published_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_for_published', to='cms.Page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
