# Generated by Django 3.2.13 on 2022-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0014_blogpostduedate_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglink',
            name='gsoc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
