# Generated by Django 2.1.8 on 2019-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0016_comment")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="proposal_confirmed",
            field=models.BooleanField(default=False),
        )
    ]
