# Generated by Django 3.2.13 on 2022-07-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0017_auto_20220713_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GsocEndDateStandard',
            new_name='GsocEndDateDefault',
        ),
    ]
