# Generated by Django 2.1.8 on 2019-05-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0018_auto_20190526_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('build_pre_blog_reminders', 'build_pre_blog_reminders'), ('build_post_blog_reminders', 'build_post_blog_reminders')], max_length=40)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('built', models.BooleanField(default=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='suborg',
            options={'ordering': ['suborg_name']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_blog_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='command',
            field=models.CharField(choices=[('send_email', 'send_email'), ('send_irc_msg', 'send_irc_msg'), ('deactivate_user', 'deactivate_user'), ('send_reg_reminder', 'send_reg_reminder'), ('add_blog_counter', 'add_blog_counter')], max_length=40),
        ),
        migrations.AddField(
            model_name='blogpostduedate',
            name='add_counter_scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsoc.Scheduler'),
        ),
        migrations.AddField(
            model_name='blogpostduedate',
            name='gsoc_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsoc.GsocYear'),
        ),
        migrations.AddField(
            model_name='blogpostduedate',
            name='post_blog_reminder_builder',
            field=models.ManyToManyField(blank=True, null=True, to='gsoc.Builder'),
        ),
        migrations.AddField(
            model_name='blogpostduedate',
            name='pre_blog_reminder_builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre', to='gsoc.Builder'),
        ),
    ]
