# Generated by Django 3.2.14 on 2022-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0019_auto_20220805_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='category',
            field=models.CharField(choices=[('build_pre_blog_reminders', 'build_pre_blog_reminders'), ('build_post_blog_reminders', 'build_post_blog_reminders'), ('build_revoke_student_perms', 'build_revoke_student_perms'), ('build_remove_user_details', 'build_remove_user_details'), ('build_add_timeline_to_calendar', 'build_add_timeline_to_calendar'), ('build_add_bpdd_to_calendar', 'build_add_bpdd_to_calendar'), ('build_add_event_to_calendar', 'build_add_event_to_calendar'), ('build_add_end_to_calendar', 'build_add_end_to_calendar'), ('build_add_end_standard_to_calendar', 'build_add_end_standard_to_calendar'), ('build_add_start_to_calendar', 'build_add_start_to_calendar'), ('build_evaluation_reminder', 'build_evaluation_reminder')], max_length=40),
        ),
    ]
