# Generated by Django 2.1.8 on 2019-05-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0020_auto_20190529_1759")]

    operations = [
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gsoc_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gsoc.GsocYear"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="blogpostduedate", name="gsoc_year"),
        migrations.RemoveField(model_name="blogpostduedate", name="title"),
        migrations.AlterField(
            model_name="blogpostduedate", name="date", field=models.DateField()
        ),
        migrations.AlterField(
            model_name="blogpostduedate",
            name="post_blog_reminder_builder",
            field=models.ManyToManyField(blank=True, to="gsoc.Builder"),
        ),
        migrations.AddField(
            model_name="blogpostduedate",
            name="timeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gsoc.Timeline",
            ),
        ),
    ]
