# Generated by Django 2.1.9 on 2019-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0024_auto_20190607_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='command',
            field=models.CharField(choices=[('send_email', 'send_email'), ('send_irc_msg', 'send_irc_msg'), ('deactivate_user', 'deactivate_user'), ('send_reg_reminder', 'send_reg_reminder'), ('add_blog_counter', 'add_blog_counter'), ('add_calendar_event', 'add_calendar_event')], max_length=40),
        ),
    ]
