# Generated by Django 2.1.9 on 2019-06-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0027_auto_20190608_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostduedate',
            name='title',
            field=models.CharField(default='Weekly Blog Post Due', max_length=100),
        ),
    ]
