# Generated by Django 2.1.9 on 2019-06-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0029_suborgdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborgdetails',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborgdetails',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborgdetails',
            name='chat',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborgdetails',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Any other link'),
        ),
        migrations.AddField(
            model_name='suborgdetails',
            name='mailing_list',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='suborgdetails',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
