# Generated by Django 2.1.9 on 2019-06-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0030_auto_20190614_0559")]

    operations = [
        migrations.AlterField(
            model_name="suborgdetails",
            name="accepted",
            field=models.BooleanField(default=None, null=True),
        )
    ]
