# Generated by Django 2.1.9 on 2019-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0032_auto_20190621_0347")]

    operations = [
        migrations.AlterField(
            model_name="suborgdetails",
            name="ideas_list",
            field=models.URLField(verbose_name="Ideas List"),
        )
    ]
