# Generated by Django 2.1.9 on 2019-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0033_auto_20190623_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgdetails',
            name='chat',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='mailing_list',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
