# Generated by Django 2.1.9 on 2019-07-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gsoc", "0040_auto_20190703_0617")]

    operations = [
        migrations.RenameField(
            model_name="suborgdetails",
            old_name="last_updated_at",
            new_name="last_reviewed_at",
        ),
        migrations.RenameField(
            model_name="suborgdetails",
            old_name="last_updated_by",
            new_name="last_reviewed_by",
        ),
    ]
