# Generated by Django 2.1.10 on 2019-07-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0043_blogpostduedate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='command',
            field=models.CharField(choices=[('send_email', 'send_email'), ('send_irc_msg', 'send_irc_msg'), ('revoke_student_permissions', 'revoke_student_permissions'), ('send_reg_reminder', 'send_reg_reminder'), ('add_blog_counter', 'add_blog_counter'), ('update_site_template', 'update_site_template'), ('archive_gsoc_pages', 'archive_gsoc_pages')], max_length=40),
        ),
    ]
