# Generated by Django 2.1.10 on 2019-07-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0046_sendemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
