# Generated by Django 2.1.10 on 2019-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0047_sendemail_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglink',
            name='send_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
