# Generated by Django 2.1.10 on 2019-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0049_blogposthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgdetails',
            name='mentors_student_engagement',
            field=models.TextField(blank=True, null=True, verbose_name='How will you keep mentors engaged with their students?'),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='reason_for_participation',
            field=models.TextField(blank=True, null=True, verbose_name='Why does your org want to participate in Google Summer of Code?'),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='students_involvement_after',
            field=models.TextField(blank=True, null=True, verbose_name='How will you keep students involved with your community after GSoC?'),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='students_involvement_gsoc',
            field=models.TextField(blank=True, null=True, verbose_name='How will you get your students involved in your community during GSoC?'),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='students_on_schedule',
            field=models.TextField(blank=True, null=True, verbose_name='How will you help your students stay on schedule to complete their projects?'),
        ),
    ]
