# Generated by Django 2.1.10 on 2019-08-14 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gsoc", "0050_auto_20190809_0529"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaddUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="builder",
            name="category",
            field=models.CharField(
                choices=[
                    ("build_pre_blog_reminders", "build_pre_blog_reminders"),
                    ("build_post_blog_reminders", "build_post_blog_reminders"),
                    ("build_revoke_student_perms", "build_revoke_student_perms"),
                    ("build_remove_user_details", "build_remove_user_details"),
                ],
                max_length=40,
            ),
        ),
    ]
