# Generated by Django 2.1.10 on 2019-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0051_auto_20190814_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_handle',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
