# Generated by Django 2.1.11 on 2019-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0053_auto_20190815_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgdetails',
            name='suborg_admin_2_email',
            field=models.EmailField(blank=True, help_text='Fill this if there are other suborg admins other than you', max_length=254, null=True, verbose_name='Suborg admin 2 email'),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='suborg_admin_3_email',
            field=models.EmailField(blank=True, help_text='Fill this if there are other suborg admins other than you', max_length=254, null=True, verbose_name='Suborg admin 3 email'),
        ),
    ]
