# Generated by Django 2.2.7 on 2020-01-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0054_auto_20190817_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborgdetails',
            name='link',
        ),
        migrations.AddField(
            model_name='suborgdetails',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='Homepage'),
        ),
    ]
