# Generated by Django 2.2.12 on 2020-04-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0055_auto_20200109_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gsoc_invited',
            field=models.BooleanField(default=False),
        ),
    ]
