# Generated by Django 3.0.7 on 2020-07-01 00:00

from django.db import migrations, models
import django.db.models.deletion

def update_keys(apps, schema_editor):
    Years = apps.get_model('gsoc', 'gsocyear')
    mapping = {y.id:y.gsoc_year for y in Years.objects.all()}

    # First, create year:year keys
    for key in mapping:
        year = Years(id = mapping[key], gsoc_year = mapping[key])
        mapping[key] = year

    # Update forign keys
    for model in ['reglink', 'suborgdetails', 'timeline', 'userprofile']:
        for record in apps.get_model('gsoc', model).objects.all():
            record.gsoc_year = mapping[record.id]

    # TODO Need to update ManyToMany fields:
    #  SubOrgDetails.past_years
    #  SubOrgDetails.applied_but_not_selected

    # Delete old keys
    for year_id in mapping:
        Years.objects.filter(id=year_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc', '0057_auto_20200427_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsocyear',
            name='gsoc_year',
            field=models.IntegerField(unique=True),
        ),
        migrations.RenameField('reglink', 'user_gsoc_year', 'gsoc_year'),

        # Update forign keys
        migrations.RunPython(update_keys),
        
        migrations.AlterField(
            model_name='reglink',
            name='gsoc_year',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='gsoc.GsocYear',
                to_field='gsoc_year'),
        ),
        migrations.AlterField(
            model_name='suborgdetails',
            name='gsoc_year',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='suborg_details',
                to='gsoc.GsocYear',
                to_field='gsoc_year'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='gsoc_year',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='gsoc.GsocYear',
                to_field='gsoc_year'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gsoc_year',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='gsoc.GsocYear',
                to_field='gsoc_year'),
        ),
        migrations.RemoveField(
            model_name='gsocyear',
            name='id',
        ),
    	migrations.AlterField(
            model_name='gsocyear',
            name='gsoc_year',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
