# Generated by Django 2.1.8 on 2019-05-06 07:37

from django.db import migrations, models
import django.db.models.deletion
import suborg_form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SuborgSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('reference_id', models.CharField(default='', editable=False, max_length=36)),
                ('is_proved', models.BooleanField(default=False)),
                ('name', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('short_description', models.TextField(null=True)),
                ('opensource_license', models.IntegerField(choices=[(0, 'others')], default=0)),
                ('potential_mentor_number', models.IntegerField(default=0)),
                ('admin_email', models.EmailField(max_length=254, null=True)),
                ('is_suborg', models.BooleanField(default=True)),
                ('logo', models.ImageField(null=True, upload_to='suborg_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='SuborgTextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='suborgtextquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suborg_form.TextQuestion'),
        ),
        migrations.AddField(
            model_name='suborgtextquestion',
            name='suborg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suborg_form.SuborgSubmission'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='suborg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suborg_form.SuborgSubmission'),
        ),
    ]
