# Generated by Django 2.1.8 on 2019-05-06 08:08

from django.db import migrations, models
import suborg_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('suborg_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborgsubmission',
            name='reference_id',
            field=models.TextField(default=suborg_form.models.gen_reference_id, editable=False),
        ),
    ]
