# Generated by Django 2.1.8 on 2019-05-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suborg_form', '0002_auto_20190506_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuborgContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.IntegerField(default=0)),
                ('link', models.TextField(default='')),
                ('suborg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suborg_form.SuborgSubmission')),
            ],
        ),
    ]
